name: Node.js CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - uses: actions/cache@v1
      id: cache
      with:
        path: |
          ~/.npm
          node_modules
        key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-node-
    - run: npm ci
    - run: npm run build --if-present
    - run: npm test
      env:
        CI: true
    - uses: GoogleCloudPlatform/github-actions/setup-gcloud@master
      with:
        version: '284.0.0'
        service_account_key: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS}}
    - name: Deploy
      if: github.ref == 'refs/heads/master'
      run: FIREBASE_TOKEN=$(gcloud auth print-access-token) npm run deploy